variables:
  service_name: monitoring-service-discovery
  short_service_name: msd
  service_base_path: monitoring-sd
  product_display_name: Monitoring Service Discovery
  product_description: Monitors all the things

