variables:
  service_name: monitoring-service-discovery
  service_base_path: monitoring-service-discovery
  short_service_name: monitoring-sd
  product_display_name: Monitoring Service Discovery
  product_description: Monitoring Service Discovery
  spec_file: monitoring-service-discovery.json
